/**
 * @module store-lang
 * Alpine.js i18n store — all EN/ES translations.
 * Usage: registerLangStore(Alpine) inside alpine:init
 */

/** @param {import('alpinejs').Alpine} Alpine */
export function registerLangStore(Alpine) {
    Alpine.store('lang', {
        current: 'en',
        t(key) {
            return this.translations[this.current][key] || key;
        },
        set(lang) {
            this.current = lang;
        },
        translations: {
            en: {
                nav_why: "Why us?",
                nav_showroom: "Showroom",
                nav_pricing: "Pricing",
                nav_faq: "FAQ",
                nav_contact: "Get in touch!",
                hero_title_1: "STOP THE SCROLL.",
                hero_title_2: "GET THE CLICK.",
                hero_desc: "We design thumbnails that bypass logic and target the viewer's instinct.",
                btn_pricing: "VIEW PRICING",
                btn_gallery: "SEE GALLERY",
                trusted_by: "TRUSTED BY",
                creators: "CREATORS",
                real_results: "Real results from real channels",
                showroom_essential: "For channels who look for functional thumbnails and manage many uploads per month without sacrificing quality.",
                showroom_pro: "For enthusiast videos with a top-notch mastery thumbnail... designed for high-budget storytelling and extreme complexity.",
                why_us_title: "Why us?",
                why_us_desc: "We don't just \"make images\". We engineer points of interest that force a click through data-backed design patterns.",
                why_us_quote: "\"A thumbnail is 90% of your success. We handle that 90% with mastery.\"",
                delivery_title: "24H DELIVERY",
                delivery_desc: "Your upload schedule is sacred. We deliver high-quality drafts within 24-48 hours, guaranteed.",
                edits_title: "UNLIMITED EDITS",
                edits_desc: "We iterate until it hits your exact vision. No extra charges, no friction. Just results.",
                warranty_title: "MONEY WARRANTY",
                warranty_desc: "Not feeling the draft? We offer a total refund. We believe in our quality that much.",
                ctr_title: "CTR PSYCHOLOGY",
                ctr_desc: "Applying color theory, facial expression analysis, and elite framing to stop the scroll.",
                workflow_title: "The ",
                workflow_word: "Workflow",
                workflow_desc: "Easy, simple and quick, asking for a thumbnail doesn't mean a head-ache",
                step1_title: "CHOOSE A PLAN",
                step1_desc: "Select the tier that fits your content strategy and goals.",
                step2_title: "SECURE PAY",
                step2_desc: "Fast and secure payments via Payoneer, Zinli, PayPal and Crypto.",
                step3_title: "SEND THE BRIEF",
                step3_desc: "Provide details for your first thumbnail.",
                step4_title: "REVISE",
                step4_desc: "You get the draft in less than 48h. We tweak every detail until it's a verified click-magnet.",
                step5_title: "DONE!",
                step5_desc: "Final files delivered in ultra-high resolution. Ready to scale.",
                btn_choose_plan: "Choose a plan",
                essential_title: "Essential ",
                essential_word: "Plans",
                starter_title: "Starter",
                starter_credits: "1 thumbnail credit",
                starter_features: ["✓ 1 Functional Design", "✓ 24h Delivery", "✓ 2 Revision rounds", "✓ Money Warranty"],
                master_title: "Master",
                master_credits: "8 thumbnail credits",
                master_features: ["✓ 8 Functional Designs", "✓ Priority Allocation", "✓ Unlimited Revisions", "✓ Money Warranty", "EXCLUSIVE_MASTER_BUNDLE"],
                growth_title: "Growth",
                growth_credits: "4 thumbnail credits",
                growth_features: ["✓ 4 Functional Designs", "✓ Strategy Insight", "✓ 4 Revision Rounds", "✓ Money Warranty"],
                select_plan: "Select Plan",
                pay_with: "Pay with",
                save_160: "SAVE $120",
                save_60: "SAVE $20",
                rush_title: "Exclusive Rush Rate",
                rush_desc: "10% OFF for rush orders",
                master_bundle_title: "EXCLUSIVE MASTER PERKS",
                access_zap: "Access to ZAP",
                by_prominiaturas: "By Pro Miniaturas",
                soon: "Soon",
                pro_plans_title: "PRO ",
                pro_plans_word: "Plans",
                pro_desc: "For agencies and creators who need high-volume, top-tier thumbnail production.",
                apex_credits: "1 PRO thumbnail credit",
                apex_features: ["✓ 3D Blender Sketch", "✓ Top notch AI", "✓ Dedicated Designer", "✓ Custom Asset Creation", "✓ 2 Revision rounds", "✓ Money Warranty"],
                empire_credits: "4 PRO thumbnail credits",
                empire_features: ["✓ 4 Elite Masterpieces", "✓ 3D Blender Sketch", "✓ Top notch AI", "✓ Dedicated Designer", "✓ Strategic Consultation", "✓ Unlimited Revisions", "✓ Money Warranty", "EXCLUSIVE_EMPIRE_BUNDLE"],
                best_value: "BEST VALUE",
                // Coming Soon keys
                coming_soon_title: "COMING ",
                coming_soon_word: "SOON",
                coming_soon_desc: "We are curating a collection of our most ambitious, high-budget work. Detailed 3D environments, complex storytelling, and extreme visual engineering.",
                under_construction: "Under Construction",
                elite_tiers_title: "ELITE TIERS ",
                elite_tiers_word: "EVOLVING",
                elite_tiers_desc: "The Apex and Empire tiers are being reconstructed to offer an even more comprehensive service for top-tier creators.",
                feat_3d_env: "3D Environments",
                feat_custom_model: "Custom complex angles",
                feat_art_dir: "Art Direction",
                faq_title: "Questions? Answers:",
                faq_desc: "Can't find the answer you're looking for? Reach out to our team directly via our <a href='#contact' class='text-[var(--purple-dark)] underline hover:text-[var(--purple)] transition-colors'>contact form</a>.",
                q1: "What information do I need to provide you to create a thumbnail?",
                a1: "Video topic, quick sum-up, and some questions replied.",
                q2: "Do you help me brainstorm a thumbnail concept?",
                a2: "Yep, that's exactly why we're here for you, you don't waste your time by finding how to create a functional design, that's all on us.",
                q3: "Do you work with YouTube clients of all sizes?",
                a3: "Yes, and that's why we have 2 pricing plans:<br><br>Essential for being a budget-friendly plan plus catchy thumbnails to help you grow when you're starting. This plan is also available for any niche.<br><br>And PRO which is for more enthusiast content creators, and people who look for very specific thumbnail poses and/or hyper realistic thumbnails.<br><br>2 Plans, 2 options = Fit your budget, get results.",
                q4: "How do I pay?",
                a4: "Once you reach out, we'll request some information for the invoice and send you a payment link.<br><br><strong>Payment methods accepted:</strong><br><br>Main ones: Payoneer, Zinli, PayPal (All these allow you to use any card from anywhere; listed in priority order).<br><br>Secondary: Binance Pay, AirTM, Cryptos.",
                q5: "What is a 3D blender sketch?",
                a5: "For PRO thumbnails to ensure the realism needed, we work on realistic environments created in Blender with custom 3D models, so you get an accurate idea for the final result.",
                q6: "Can I get a free trial?",
                a6_p1: "Yes! If you meet these requirements:",
                a6_l1: "+100k subscribers.",
                a6_l2: "Consistency (posting at least once/week)",
                q7: "Do you deliver the editable source files (PSD)?",
                a7: "We reserve the source files to protect our proprietary design methods and techniques. However, if specifically requested, we can prepare a clean, organized PSD file for an additional fee.",
                q8: "What counts as a revision?",
                a8: "Adjustments to font, colors, lighting, or moving elements around within the same concept. Changing the entire idea/direction of the thumbnail counts as a new design credit.",
                q9: "How fast are revisions delivered?",
                a9: "Much faster than the first draft. We prioritize edits to typically deliver them within less than 1 hour.",
                q10: "What is a Rush Fee?",
                a10: "A Rush Fee is an optional surcharge for prioritized, urgent delivery.<br><br><strong>Standard Rate:</strong> +120% surcharge (e.g. $40 thumbnail + $48 fee).<br><br><strong>Master &amp; Empire Rate:</strong> Reduced +110% surcharge (e.g. $40 thumbnail + $44 fee).",
                q11: "How can I request an urgent delivery? (rush fee)",
                a11: "<strong>Existing Clients:</strong> Just send a message via communication platform we've been using.<br><br><strong>New Clients:</strong> Fill the form, mention your plan, and specify you need a rush delivery. We'll proceed to the payment phase once completed we'll start immediately with your thumbnail.",
                ready_takeoff: "Ready for ",
                takeoff_word: "Takeoff?",
                fill_form: "Fill the form and let's work on your next thumbnail",
                sent_msg: "SENT!",
                contact_soon: "Sent! Please check your inbox (and SPAM folder) for your copy.",
                outside_hours: "We typically reply within 2-3 hours during our working days (Mon to Fri).",
                send_new: "Send new Inquire",
                name_holder: "Name",
                email_holder: "Email",
                msg_holder: "tell us about your channel...",
                send_inq: "Send Inquiry",
                contact: "Contact",
                our_socials: "Our Socials",
                rights: "© 2026 PRO MINIATURAS • ALL CLICKS RESERVED",
                footer_desc: "PRO Miniaturas is a design agency specializing in high-CTR thumbnails for YouTube creators.",
                footer_business: "For business inquiries, please prefer @prominiaturas.com email or just fill the form.",
                about_us: "About Us",
                about_desc: "Professional visual design for creators and brands worldwide.",
                get_help: "Get Help",
                read_faq: "Read our FAQ",
                chat_ig: "Chat via Instagram",
                links: "Links",
                footer_workflow: "The Workflow",
                t1_text: "Thank you so much for everything because you are a very respectful person and never contradicted my ideas and in fact took them all into account. I found this very good... Thank you very much for all your good work.",
                t1_author: "Arsenia Fernandez-Uckele",
                t1_role: "Creator",
                lewis_text: "Michael and his team have been creating thumbnails for my channel for a long time now and we've seen incredible results. Not only are the designs professional and eye-catching, a lot of the time his team think of things you wouldn't of. Couldn't recommend him more.",
                lewis_author: "Lewis Menelaws",
                lewis_role: "Creator | Coding With Lewis",
                mitchell_text: "I have worked with proministuras for about a year now and took my channel from averaging 2-3% Ctr to now 6-8% Ctr. If you're wanting more views on YouTube this is the only person I would recommend.",
                mitchell_author: "Mitchell Wright",
                mitchell_role: "Creator",
                t6_text: "Working with Pro Miniaturas has been an absolute game changer for my YouTube channel. He consistently exceeds my expectations and brings even my wildest ideas to life exactly how I picture them. His turnaround time is fast, his communication is incredible, and he's always open to feedback.\n\nMost importantly, switching to him for thumbnails has had a real, noticeable impact on the engagement and performance of my videos. I couldn't recommend him more.",
                t6_author: "Zach McDermott",
                t6_role: "Agency owner | Spark Media Management",
                select_msg_start: "Hi! I'm interested on",
                select_msg_end: "plan, please send over the invoice link so I'm paying asap"
            },
            es: {
                nav_why: "¿Por qué nosotros?",
                nav_showroom: "Portafolio",
                nav_pricing: "Precios",
                nav_faq: "FAQ",
                nav_contact: "¡Contáctanos!",
                hero_title_1: "DETÉN EL SCROLL.",
                hero_title_2: "TEN EL CLICK.",
                hero_desc: "Diseñamos miniaturas que evaden la lógica y apuntan al instinto del espectador.",
                btn_pricing: "VER PRECIOS",
                btn_gallery: "VER GALERÍA",
                trusted_by: "CONFIADO POR",
                creators: "CREADORES",
                real_results: "Resultados reales de canales reales",
                showroom_essential: "Para canales que buscan miniaturas funcionales y manejan mucha demanda por mes sin sacrificar calidad.",
                showroom_pro: "Para canales entusiastas con una miniatura de primer nivel... diseñado para videos de alto presupuesto.",
                why_us_title: "¿Por qué nosotros?",
                why_us_desc: "No solo \"hacemos imágenes\". Diseñamos puntos de interés que fuerzan el click a través de patrones de diseño respaldados por datos.",
                why_us_quote: "\"Una miniatura es el 90% de tu éxito. Manejamos ese 90% con excelencia.\"",
                delivery_title: "ENTREGA 24H",
                delivery_desc: "Tu calendario de subidas es sagrado. Entregamos borradores de alta calidad en 24-48 horas, garantizado.",
                edits_title: "EDICIONES ILIMITADAS",
                edits_desc: "Iteramos hasta que coincida con tu visión exacta. Sin cargos extra, sin fricción. Solo resultados.",
                warranty_title: "GARANTÍA DE REEMBOLSO",
                warranty_desc: "¿No te convence el borrador? Ofrecemos un reembolso total. Creemos en nuestra calidad así de mucho.",
                ctr_title: "PSICOLOGÍA DE CTR",
                ctr_desc: "Aplicando teoría del color, análisis de expresiones faciales y encuadre de élite para detener el scroll.",
                workflow_title: "El ",
                workflow_word: "Proceso",
                workflow_desc: "Fácil, simple y rápido, hacer una miniatura no significa un dolor de cabeza",
                step1_title: "ELIGE UN PLAN",
                step1_desc: "Selecciona el nivel que se ajuste a tu estrategia de contenido y metas.",
                step2_title: "PAGO SEGURO",
                step2_desc: "Pagos rápidos y seguros vía Payoneer, PayPal o facturas Kontigo.",
                step3_title: "ENVÍA EL BRIEF",
                step3_desc: "Proporciona detalles para tu primera miniatura.",
                step4_title: "REVISIÓN",
                step4_desc: "Recibes el borrador en menos de 48h. Ajustamos cada detalle hasta que sea un imán de clicks verificado.",
                step5_title: "¡LISTO!",
                step5_desc: "Archivos finales entregados en ultra-alta resolución. Listos para escalar.",
                btn_choose_plan: "Elegir plan",
                essential_title: "Essential ",
                essential_word: "Plans",
                starter_title: "Starter",
                starter_credits: "1 crédito de miniatura",
                starter_features: ["✓ 1 Diseño Funcional", "✓ Entrega 24h", "✓ 2 Rondas de revisión", "✓ Garantía de Reembolso"],
                master_title: "Master",
                master_credits: "8 créditos de miniatura",
                master_features: ["✓ 8 Diseños Funcionales", "✓ Asignación Prioritaria", "✓ Revisiones Ilimitadas", "✓ Garantía de Reembolso", "EXCLUSIVE_MASTER_BUNDLE"],
                growth_title: "Growth",
                growth_credits: "4 créditos de miniatura",
                growth_features: ["✓ 4 Diseños Funcionales", "✓ Insight de Estrategia", "✓ 4 Rondas de revisión", "✓ Garantía de Reembolso"],
                select_plan: "Seleccionar Plan",
                pay_with: "Pagar con",
                save_160: "AHORRA $120",
                save_60: "AHORRA $20",
                rush_title: "Tarifa Rush Exclusiva",
                rush_desc: "10% de descuento entregas urgentes",
                master_bundle_title: "BENEFICIOS EXCLUSIVOS MASTER",
                access_zap: "Acceso a ZAP",
                by_prominiaturas: "Por Pro Miniaturas",
                soon: "Pronto",
                pro_plans_title: "PRO ",
                pro_plans_word: "Plans",
                pro_desc: "Para agencias y creadores que necesitan producción de alto volumen y nivel superior.",
                apex_credits: "1 crédito de miniatura PRO",
                apex_features: ["✓ Boceto 3D Blender", "✓ Top notch AI", "✓ Diseñador dedicado", "✓ Creación de Activos Custom", "✓ 2 rondas de revisión", "✓ Garantía de Reembolso"],
                empire_credits: "4 créditos de miniatura PRO",
                empire_features: ["✓ 4 Obras Maestras Elite", "✓ Boceto 3D Blender", "✓ Top notch AI", "✓ Diseñador dedicado", "✓ Consultoría Estratégica", "✓ Revisiones Ilimitadas", "✓ Garantía de Reembolso", "EXCLUSIVE_EMPIRE_BUNDLE"],
                best_value: "MEJOR VALOR",
                // Coming Soon keys
                coming_soon_title: "MUY ",
                coming_soon_word: "PRONTO",
                coming_soon_desc: "Estamos seleccionando una colección de nuestros trabajos más ambiciosos y de alto presupuesto. Entornos 3D personalizados, ángulos complejos, storytelling complejo e ingeniería visual extrema.",
                under_construction: "En Construcción",
                elite_tiers_title: "PLANES ELITE ",
                elite_tiers_word: "EVOLUCIONANDO",
                elite_tiers_desc: "Los planes Apex y Empire están siendo reconstruidos para ofrecer un servicio aún más completo para creadores de alto nivel.",
                feat_3d_env: "Entornos 3D",
                feat_custom_model: "Ángulos complejos personalizados",
                feat_art_dir: "Dirección de Arte",
                faq_title: "¿Preguntas? Respuestas:",
                faq_desc: "¿No encuentras la respuesta que buscas? Contacta directamente a nuestro equipo a través del <a href='#contact' class='text-[var(--purple-dark)] underline hover:text-[var(--purple)] transition-colors'>formulario de contacto</a>.",
                q1: "¿Qué información necesito darte para crear una miniatura?",
                a1: "Tema del video, resumen rápido y algunas preguntas respondidas.",
                q2: "¿Me ayudan a pensar el concepto de la miniatura?",
                a2: "Sí, exactamente para eso estamos. No pierdas tiempo pensando cómo hacer un diseño funcional, eso déjanoslo a nosotros.",
                q3: "¿Trabajan con canales de YouTube de todos los tamaños?",
                a3: "Sí, y por eso tenemos 2 planes de precios:<br><br>Essential es un plan económico con miniaturas llamativas para ayudarte a crecer cuando estás empezando. Este plan también está disponible para cualquier nicho.<br><br>Y PRO, que es para creadores de contenido más entusiastas y personas que buscan poses muy específicas o miniaturas hiperrealistas.<br><br>2 Planes, 2 opciones = Se ajusta a tu presupuesto, obtén resultados.",
                q4: "¿Cómo pago?",
                a4: "Una vez nos contactes, solicitaremos información para la factura y te enviaremos un enlace de pago.<br><br><strong>Métodos de pago aceptados:</strong><br><br>Principales: Payoneer, Zinli, PayPal (Puedes usar cualquier tarjeta desde cualquier lugar; listados en orden de prioridad).<br><br>Secundarios: Binance Pay, AirTM, Criptos.",
                q5: "¿Qué es un boceto 3D en Blender?",
                a5: "Para miniaturas PRO, para asegurar el realismo, trabajamos en entornos realistas creados en Blender con modelos 3D custom, para que tengas una idea precisa de la miniatura.",
                q6: "¿Puedo tener una prueba gratis?",
                a6_p1: "¡Sí! Si cumples estos requisitos:",
                a6_l1: "+100k suscriptores.",
                a6_l2: "Consistencia (publicar al menos una vez/semana)",
                q7: "¿Entregan el archivo editable (PSD)?",
                a7: "Nos reservamos compartir los archivos fuente para proteger nuestros métodos y secretos de diseño. Sin embargo, si es explícitamente requerido, podemos preparar un archivo PSD limpio y organizado por un costo adicional.",
                q8: "¿Qué cuenta como una revisión?",
                a8: "Ajustes de fuente, colores, iluminación o mover elementos dentro del mismo concepto. Cambiar la idea o dirección completa de la miniatura cuenta como un nuevo crédito de diseño.",
                q9: "¿Qué tan rápido entregan las revisiones?",
                a9: "Mucho más rápido que el primer borrador. Priorizamos las ediciones para entregártelas típicamente en menos de 1 hora.",
                q10: "¿Qué es un Rush Fee?",
                a10: "El Rush Fee es un cargo opcional por entrega prioritaria y urgente.<br><br><strong>Tarifa Estándar:</strong> Recargo de +120% (ej. miniatura de $40 + cargo de $48).<br><br><strong>Tarifa Master y Empire:</strong> Recargo reducido de +110% (ej. miniatura de $40 + cargo de $44).",
                q11: "¿Cómo solicito una entrega urgente? (rush fee)",
                a11: "<strong>Clientes Existentes:</strong> Envía un mensaje vía plataforma de comunicación que usamos.<br><br><strong>Nuevos Clientes:</strong> Llena el formulario, menciona tu plan y especifica que necesitas entrega urgente, procederemos a la fase de pago una vez finalizada comenzaremos inmediatamente con tu miniatura.",
                ready_takeoff: "¿Listo para el ",
                takeoff_word: "Despegue?",
                fill_form: "Llena el formulario y a trabajar en tu próxima miniatura",
                sent_msg: "¡ENVIADO!",
                contact_soon: "¡Enviado! Por favor revisa tu bandeja de entrada (y carpeta de SPAM) para ver tu copia.",
                outside_hours: "Solemos responder en 2-3 horas durante nuestros días laborales (Lunes a Viernes).",
                send_new: "Enviar nueva consulta",
                name_holder: "Nombre",
                email_holder: "Email",
                msg_holder: "cuéntanos sobre tu canal...",
                send_inq: "Enviar Consulta",
                about_us: "Nosotros",
                about_desc: "Diseño visual profesional para creadores y marcas de todo el mundo.",
                get_help: "Ayuda",
                read_faq: "Lee nuestras FAQ",
                chat_ig: "Chat vía Instagram",
                links: "Enlaces",
                footer_workflow: "El proceso",
                contact: "Contacto",
                our_socials: "Síguenos",
                rights: "© 2026 PRO MINIATURAS • TODOS LOS CLICKS RESERVADOS",
                footer_desc: "PRO Miniaturas es una agencia de diseño especializada en miniaturas de alto CTR para creadores de YouTube.",
                footer_business: "Para negocios, por favor prefiere un email @prominiaturas.com o llena el formulario.",
                t1_text: "Muchísimas gracias por todo porque usted es una persona muy respetuosa y nunca contradijo mis ideas y de hecho las tomaba en cuenta todas. Esto me pareció muy bueno... Muchas gracias por todo su buen trabajo.",
                t1_author: "Arsenia Fernandez-Uckele",
                t1_role: "Creadora",
                lewis_text: "Michael y su equipo han estado creando miniaturas para mi canal desde hace mucho tiempo y hemos visto resultados increíbles. No solo los diseños son profesionales y llamativos, sino que muchas veces su equipo piensa en cosas que a uno no se le ocurrirían. No podría recomendarlos más.",
                lewis_author: "Lewis Menelaws",
                lewis_role: "Creador | Coding With Lewis",
                mitchell_text: "He trabajado con proministuras por un año y mi canal pasó de un CTR promedio de 2-3% a 6-8%. Si quieres más vistas en YouTube, esta es la única persona que recomendaría.",
                mitchell_author: "Mitchell Wright",
                mitchell_role: "Creador",
                t6_text: "Trabajar con Pro Miniaturas ha sido un cambio absoluto para mi canal de YouTube. Constantemente superan mis expectativas y dan vida incluso a mis ideas más locas exactamente como las imagino. Su tiempo de respuesta es rápido, su comunicación es increíble y siempre están abiertos a comentarios.\n\nLo más importante, cambiar a ellos para las miniaturas tuvo un impacto real y notable en la participación y el rendimiento de mis videos. No podría recomendarlos más.",
                t6_author: "Zach McDermott",
                t6_role: "Dueño de agencia | Spark Media Management",
                btn_gallery: "VER GALERÍA",
                select_msg_start: "¡Hola! Me interesa el plan",
                select_msg_end: ", por favor envíame el enlace de pago para hacerlo lo más pronto posible."
            }
        }
    });
}
